#include<iostream.h>
#include<conio.h>
main()
{
clrscr();
int a,d;
int b=2,c;
	cout<<"program to convert number into binary form"<<"\n";
	cout<<"enter an number"<<"\n";
	cin>>a;
	cout<<"quotient of number"<<"\n";
	c=a%b;

	cout<<"c="<<c<<"\n";
       {for(int j=0;j<=c;j++)
	cout<<"remainder of number"<<"\n";
	d=a/b;
	}
       for(int i=0;i<=d;i++)
	{
	cout<<"d="<<d<<"\n";
}
getch();
return 0;
}