#include<iostream.h>
#include<conio.h>
main()
{
clrscr();
int num,i,c,even,odd;
	cout<<"enter a number"<<"\n";
	cin>>num>>"\n";
	for(i=1;i<=10;++i)
	{ c=num*i;
	  cout<<"\n"<<c; }
	cout<<"	     \n"	;
	cout<<"\t";

	cin>>num>>"\n";
	for(i=1;i<=10;++i)
	{ c=num*i;
	  cout<<"\n"<<c; }
	cout<<"		\n"	;
	cout<<"\t";

	cin>>num>>"\n";
	for(i=1;i<=10;++i)
	{ c=num*i;
	  cout<<"\n"<<c; }
	cout<<"		\n"	;
	cout<<"\t";

	cin>>num>>"\n";
	for(i=1;i<=10;++i)
	{ c=num*i;
	  cout<<"\n"<<c; }
	cout<<"		\n"	;
	cout<<"\t";

	cin>>num>>"\n";
	for(i=1;i<=10;++i)
	{ c=num*i;
	  cout<<"\n"<<c; }
	cout<<"		\n	";
	cout<<"\t";
getch();
return 0;
}